name: Compile Blockchain

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libboost-all-dev libssl-dev libzmq5-dev libhidapi-dev libreadline-dev
        
    - name: Direct compilation
      run: |
        mkdir -p build && cd build
        
        # Compile core blockchain files with correct paths
        g++ -std=c++17 -O2 -static -Wall -Werror \
          -I../include \
          $(find ../src/ -name "*.cpp" | head -20) \
          -lboost_system -lboost_filesystem -lboost_thread -lssl -lcrypto \
          -lzmq -lhidapi -lreadline \
          -o rsdt-blockchain
        
        # Create bin directory for artifacts
        mkdir -p bin
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: blockchain-binaries
        path: build/bin/
