name: Compile Wallets and Binaries

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false  # Skip submodules to avoid issues
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libboost-all-dev libssl-dev libzmq5-dev libhidapi-dev libreadline-dev ccache
        
    - name: Set up ccache
      run: |
        ln -s /usr/bin/ccache /usr/local/bin/gcc
        ln -s /usr/bin/ccache /usr/local/bin/g++
        
    - name: Compile blockchain
      run: |
        # Create build directory and compile with simplified flags
        mkdir -p build && cd build
        
        # Copy missing files or create workarounds
        echo "#include <iostream>" > ../src/version.h
        
        # Run CMake with workarounds
        cmake .. -DMANUAL_SUBMODULES=1 -DCCACHE=ON -DCMAKE_SKIP_RPATH=ON -DBUILD_TAG="github-actions" && make -j4
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: blockchain-binaries
        path: build/bin/
