name: Compile Wallets and Binaries

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libboost-all-dev libssl-dev
        
        # Install missing dependencies
        sudo apt-get install -y libzmq-dev libhidapi-dev libreadline-dev ccache
        
    - name: Set up ccache
      run: |
        ln -s /usr/bin/ccache /usr/local/bin/gcc
        ln -s /usr/bin/ccache /usr/local/bin/g++
        
    - name: Compile blockchain
      run: |
        # Initialize and update submodules
        git submodule update --init --recursive --force
        
        # Create build directory and compile
        mkdir -p build && cd build
        cmake .. -DMANUAL_SUBMODULES=1 -DCCACHE=ON && make -j4
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: blockchain-binaries
        path: build/bin/
