name: Compile Wallets and Binaries

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libboost-all-dev libssl-dev
        
    - name: Compile blockchain
      run: |
        # Initialize and update submodules
        git submodule update --init --recursive --force
        
        # Create build directory and compile
        mkdir -p build && cd build        cmake .. -DMANUAL_SUBMODULES=1 && make -j4
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: blockchain-binaries
        path: build/bin/
